on:
  push:
    branches: [ master ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 19.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 19.x
    - run: npm install
    - run: npm start
    - name: ssh deploy on aws ec2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
